Console.WriteLine("--------------------------------------------------");
Console.WriteLine(" № Название                      Цена  Кол.  Сумма");
Console.WriteLine(" 1 КОФЕ СТАНДАРТНЫЙ             69.00  1.00  69.00");
Console.WriteLine(" НДС с рассчитанной                          10.53");
Console.WriteLine(" ставкой 18%");
Console.WriteLine();
Console.WriteLine(" 2 РУЛЕТ-СПРИНГ ТВ ИЗ           70.00  1.00  70.00");
Console.WriteLine(" КУ");
Console.WriteLine(" НДС с рассчитанной                           6.36");
Console.WriteLine(" ставкой 10%");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("--------------------------------------------------");
Console.WriteLine(" ИТОГО:                                     139.00");
Console.WriteLine();
Console.WriteLine(" Электронные средства                       139.00");
Console.WriteLine(" НДС итого чека с                            10.53");
Console.WriteLine(" рассчитанной ставкой");
Console.WriteLine(" 18%");
Console.WriteLine(" НДС итого чека с                             6.36");
Console.WriteLine(" рассчитанной ставкой");
Console.WriteLine(" 10%");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("--------------------------------------------------");
Console.WriteLine(" ВИД НАЛОГООБЛОЖЕНИЯ: ОСН");
Console.WriteLine(" РЕГ. НОМЕР ККТ: 0000143873023483");
Console.WriteLine(" ЗАВОД. №:");
Console.WriteLine(" ФН №: 8710000100265168");
Console.WriteLine(" ФН №: 6026");
Console.WriteLine(" ФПД: 3322278314");
